name: Build Mod
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: Win64
          - os: ubuntu-latest
            target: Android64
          - os: macos-latest
            target: MacOS
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.target }}
          sdk: latest

  combine:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/build-geode-mod/combine@main
      - uses: actions/upload-artifact@v4
        with:
          name: FlyBrainAI-Mod
          path: ${{ steps.combine.outputs.combined-output }}
